# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/7FBA-DFAB"; # /dev/sdb1
      fsType = "vfat";
    };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/51ac2753-16b9-46fb-92da-b355c484a301"; # /dev/sdb2
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/0e67fdef-fab7-4540-be1b-cffc364aed5f"; } # /dev/sdb3
    ];

  fileSystems."/mnt/disk/boot" =
    { device = "/dev/disk/by-uuid/DC1A-1478"; # /dev/sda2
      fsType = "auto";
      mountPoint = "/mnt/disk/boot";
    };

  fileSystems."/mnt/disk/root" =
    { device = "/dev/disk/by-uuid/847bb282-126b-41f0-afc6-49f0e5779255"; # /dev/sda1
      fsType = "auto";
      mountPoint = "/mnt/disk/root";
    };



  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
