#!/bin/bash
set -e

home="$HOME"
local_backup="$home/all/Backup"
external_backups="/Volumes/Black128/Backup /Volumes/White128/Backup"
documents="Documents"
media="Media"

cd $home/all

########################################
# Print usage message & verify which backup locations are available

if [[ "$1" != "-n" && "$1" != "-y" ]]
then
  echo "Use the 1st & only arg to specify whether or not you actually want to make changes"
  echo "  -n  No I don't want to make changes, show me what the changes would be"
  echo "  -y  Yes I want to make changes, show me what changes I'm making"
  exit
fi

for bk in $local_backup $external_backups
do
  base="${bk%/*}"
  if [[ -d "$base" ]]
  then
    if [[ ! -d "$bk" ]]
    then echo "$base is mounted, creating $bk" &&  mkdir -p $bk
    else echo "$base is mounted and $bk is available"
    fi
  else echo "$base is not available!"
  fi
done

########################################
# Copy over anything from media that isn't in the media backup

# Everything in media should have a filename w/out spaces
invalid_files="`find $media -type f -name "* *"`"
if [[ -n "$invalid_files" ]]
then echo "Invalid files present: $invalid_files" && exit 1
fi

echo;echo "Copying new Media files"
for pic in `find $media -type f -not -path "*/Downloads/*" -not -path "*/screenshots/*" -not -name ".DS_Store"`
do
  # for each of our backup locations..
  for bk in $external_backups
  do
    # If this backup location is available and this picture isn't there yet..
    if [[ -d "$bk" && ! -f "$bk/$pic" ]]
    then
      # Make a copy of this picture if we're making changes
      # Otherwise just echo how we would copy it
      if [[ "$1" == "-y" ]]
      then mkdir -p `dirname "$bk/$pic"` && cp -iv "$pic" "$bk/$pic"
      else echo cp -iv "$pic" "$bk/$pic"
      fi
    fi
  done
done

########################################
# Create a single compressed archive in our first backup location

echo;echo "Creating compressed Documents backup"
name="`date +%y%m%d`-documents.tar.gz"
if [[ ! -f "$local_backup" ]]
then
  echo tar --exclude=**/node_modules -acf "$local_backup/$name" "$documents"
  if [[ "$1" == "-y" ]]
  then tar --exclude=**/node_modules -czf "$local_backup/$name" "$documents"
  fi
else
  echo "$local_backup/$name already exists"
fi

########################################
# Copy our Documents archive to the other backup locations

echo;echo "Copying $name to external backup locations"
for bk in $external_backups
do
  if [[ -d "$bk" && "$1" == "-y" ]]
  then cp -iv "$local_backup/$name" "$bk/$name"
  else echo cp -iv "$local_backup/$name" "$bk/$name"
  fi
done
