#!/bin/bash

########################################
# Add repositories to apt sources & update

# Dropbox
if ! grep dropbox /etc/apt/sources.list
then
  echo '' >> /etc/apt/sources.list
  echo '# Dropbox' >> /etc/apt/sources.list
  echo 'deb [arch=i386,amd64] http://linux.dropbox.com/ubuntu xenial main' >> /etc/apt/sources.list
  apt-key adv --keyserver pgp.mit.edu --recv-keys 1C61A2656FB57B7E4DE0F4C1FC918B335044912E
fi

# KeePassX
if [[ -z "`find /etc/apt/sources.list.d/ | grep eugenesan`" ]]
then
  sudo add-apt-repository -y ppa:eugenesan/ppa
fi

apt-get -y update

########################################
# Install everything

apt install -y \
  vim \
  git \
  curl \
  compizconfig-settings-manager \
  python-gpgme \
  dropbox \
  keepassx

apt-get -y upgrade && apt-get -y autoremove

########################################
# Vim setup

# This folder will store our temporary backup files
mkdir -p ~/.vimtmp

# folders to store plugins
mkdir -p ~/.vim/autoload
mkdir -p ~/.vim/bundle

# https://github.com/tpope/vim-pathogen
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

cd ~/.vim/bundle

git clone -q --depth=1 https://github.com/vim-syntastic/syntastic.git
git clone -q https://github.com/pangloss/vim-javascript.git
git clone -q https://github.com/mxw/vim-jsx.git
git clone https://github.com/scrooloose/nerdtree.git

