#!/bin/bash

# Environment setup
set -e
cd $HOME/all
uploads="Dropbox/Camera Uploads"
media="Media"
imports="$media/imports"
mkdir -p $imports

if [[ "$1" != "-n" && "$1" != "-y" ]]
then
  echo "Use the 1st & only arg to specify whether or not you actually want to make changes"
  echo "  -n  No I don't want to make changes, show me what the changes would be"
  echo "  -y  Yes I want to make changes, show me what changes I'm making"
  exit
fi

function getDateName {
  pic=$1
  d=`stat $1 | grep 'Modify: ' |\
    sed 's/Modify: //' |\
    sed 's/-//g' |\
    sed 's/://g' |\
    sed 's/ /-/' |\
    sed 's/^20//' |\
    sed 's/\..*//'`
  ext="${pic##*.}"
  echo "$d.$ext"
}

########################################
# Move Camera Uploads to import folder

echo
echo "Copying files from $uploads to $imports"
if [[ -n "`ls "$uploads"`" ]]
then
  if [[ "$1" == "-y" ]]
  then
    find "$uploads" -type f -not -name "*Icon" -not -name "*.dropbox" -exec mv -iv {} $imports \;
  elif [[ "$1" == "-n" ]]
  then
    find "$uploads" -type f -not -name "*Icon" -not -name "*.dropbox" -exec echo mv -iv {} $imports \;
  fi

else
  echo "$uploads is empty"
fi

########################################
# Rename all imports to a standard name

exit

echo
echo "Renaming imports to standard date names"
OIFS="$IFS"
IFS=$'\n'
for pic in `find $imports -maxdepth 1 -type f`
do
  dateName="`getDateName $pic`"
  dateDir=`echo $dateName | cut -c1-2`
  target="$media/$dateDir/$dateName"
  mkdir -p $media/$dateDir

  if [[ -f "$target" ]]
  then
    oldDateName="$dateName"
    oldTime="${oldDateName#*-}"
    leadingZeros="${oldTime%%[1-9]*}"
    dateName="${oldDateName%-*}-$leadingZeros$(( 10#${oldTime%.*} + 1 )).${oldDateName#*.}"
    echo "$oldDateName exists, renaming to $dateName"
    target="$media/$dateDir/$dateName"
  fi

  if [[ -f "$target" ]]
  then
    oldDateName="$dateName"
    oldTime="${oldDateName#*-}"
    leadingZeros="${oldTime%%[1-9]*}"
    dateName="${oldDateName%-*}-$leadingZeros$(( 10#${oldTime%.*} - 2 )).${oldDateName#*.}"
    echo "$oldDateName exists, renaming to $dateName"
    target="$media/$dateDir/$dateName"
  fi

  if [[ "$1" == "-y" ]]
  then mv -iv "$pic" "$target"
  elif [[ "$1" == "-n" ]]
  then echo mv -iv "$pic" "$target"
  fi

done
IFS="$OIFS"

echo
echo "Done!"
